### ISSUE TITLE
Expose custom fields

### ISSUE THREAD

**Issue by mjrsnyder** [fivetran/dbt_asana_source#7]
Firstly, thanks for building these packages!

Having access to custom fields would add a lot of value to the Asana data in our DW.  Would it be possible to add them as an object to the task model?  Adding them as a separate model would be fine.

I'm happy to help work on this but I would appreciate input on how best to implement it.

Thanks!

**Comment by fivetran-kristin** [comment]
Hey Charlie, thank you! If you'd like to work on this, that would be great!  Here is some info to get you going. LMK if you have any questions along the way.

--- 

A good example of how we've done this in the pass is in our salesforce model. 

Once you identify the models you'd like to include passthrough columns to, the steps include the following. I've linked examples of this work for each item.

Source package:
- Update dbt_project.yml file to include [passthrough variables](https://github.com/fivetran/dbt_salesforce_source/blob/master/dbt_project.yml#L20)
- Update staging models to utilize passthrough columns. Note this needs to be done in two places - [here](https://github.com/fivetran/dbt_salesforce_source/blob/master/models/stg_salesforce__account.sql#L25) and [here](https://github.com/fivetran/dbt_salesforce_source/blob/master/models/stg_salesforce__account.sql#L72).
[- Update README configuration to call out use of passthrough columns](https://github.com/fivetran/dbt_salesforce_source#configuration)

Transform package:
- Update dbt_project.yml file to include [passthrough columns](https://github.com/fivetran/dbt_salesforce/blob/master/dbt_project.yml#L23)
- Update any applicable models so that the passthrough columns flow through to final models.  Example of final model [here](https://github.com/fivetran/dbt_salesforce/blob/master/models/salesforce__opportunity_enhanced.sql#L51).
- Update [README](https://github.com/fivetran/dbt_salesforce#configuration)

**Comment by fivetran-kristin** [comment]
@mjrsnyder I just created new releases for the packages. You'll be able to upgrade to asana version 0.3.1 once you see it on the hub [here](https://hub.getdbt.com/fivetran/asana/latest/) (I expect this to take no less than 1 day).

**Comment by wesseljt** [comment]
@fivetran-kristin Thanks for you and are your team's responsiveness!
